apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-commander
  name: redis-commander
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: redis-commander
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
        tier: backend
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest       
        env:
        - name: REDIS_HOSTS
          value: redis:redis:6379
        - name: REDIS_PORT
          value: ""
        ports:
        - name: redis-commander
          containerPort: 8081
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: webrelay # other ingress classes will be ignored
  name: relay-ingress
spec:
  rules:
    - host: redis-cm.webrelay.io
      http:
        paths:        
        - path: /
          backend:
            serviceName: redis-commander
            servicePort: 8081
